import assert from 'node:assert/strict';
import fs from 'node:fs';

const refreshJob = fs.readFileSync(new URL('../lib/trendRefreshJob.js', import.meta.url), 'utf8');
const jobs = fs.readFileSync(new URL('../lib/jobs.js', import.meta.url), 'utf8');
const endpoint = fs.readFileSync(new URL('../pages/api/jobs/update-trends.js', import.meta.url), 'utf8');
const kv = fs.readFileSync(new URL('../lib/kv.js', import.meta.url), 'utf8');
const api = fs.readFileSync(new URL('../lib/api.js', import.meta.url), 'utf8');
const admin = fs.readFileSync(new URL('../pages/admin.js', import.meta.url), 'utf8');
const version = fs.readFileSync(new URL('../pages/api/version.js', import.meta.url), 'utf8');
const adminAction = fs.readFileSync(new URL('../pages/api/admin-action.js', import.meta.url), 'utf8');

assert.match(refreshJob, /TREND_REFRESH_STEP_BATCH_SIZE\s*=\s*1/);
assert.match(refreshJob, /TARGET_TOP_COUNT\s*=\s*PUBLIC_TOP_COUNT/);
assert.match(refreshJob, /RESEARCH_POOL_LIMIT\s*=\s*TOP_GENERATION_POOL_COUNT/);
assert.match(refreshJob, /startTrendRefreshRun/);
assert.match(refreshJob, /executeTrendRefreshBatch/);
assert.match(refreshJob, /finalizeTrendRefreshRun/);
assert.match(refreshJob, /saveTrendRunCandidates/);
assert.match(refreshJob, /getPublicationStage/);
assert.doesNotMatch(refreshJob, /acquireLock\(lockName,1200\)/, '20분짜리 단일 전역 잠금에 의존하면 안 됩니다.');
assert.match(jobs, /phase = 'start'/);
assert.match(jobs, /parallelism: 1/);
assert.match(jobs, /update-trends-v836/);
assert.match(endpoint, /phase === 'retry'/);
assert.match(endpoint, /phase === 'batch'/);
assert.match(endpoint, /phase === 'finalize'/);
assert.match(kv, /activeTrendRefresh/);
assert.match(kv, /cronRunCandidatesKey/);
assert.match(kv, /top_refresh_v2/);
assert.match(api, /ANTHROPIC_TIMEOUT_MS\|\|90000/);
assert.match(api, /trendMeta\.fastRefresh!==true/);
assert.match(admin, /CURRENT_CONTENT_VERSION=132/);
assert.match(admin, /키워드 위치/);
assert.match(admin, /중단 지점부터 재개/);
assert.match(adminAction, /resume_trend_run/);
assert.match(adminAction, /enqueueTrendRefreshStep/);
assert.match(version, /contentVersion:132/);
assert.match(version, /trendCacheVersion:51/);
assert.match(version, /fixed-keyword-content-stop-control-v8025/);
console.log('v8.0.9 resumable QStash refresh tests passed');
