import pkg from '../../package.json';

export default function handler(req,res){
  res.setHeader('Cache-Control','no-store');
  return res.status(200).json({
    appVersion:pkg.version,
    contentVersion:130,
    trendCacheVersion:50,
    engine:'fixed-keyword-top20-single-candidate-qstash-v8034',
    feedFallback:'published-content-source-of-truth-and-index-rebuild-v8030-plus-canonical-run-snapshot-alias-v8034',
    navigationFlow:'top-summary-card-to-feed-detail',
    publicCopyPolicy:'hide-research-window-phrases',
    instagramPolicy:'cover-feed-sections-insight-promo',
    publicTopPolicy:'fixed_keyword_content_v16_top20',
    topKeywordPolicy:'v8020-relative-ranking-fixed-20-with-invalid-fragment-exclusion-v8034',
    keywordExtractionPolicy:'single-representative-entity-and-headline-fragment-rejection-v8034',
    contentPolicy:'keyword-identity-or-current-issue',
    stopControl:'admin-immediate-cancel-stop-flag-task-stop-and-qstash-publication-block-v8030',
    adminRuntime:'missing-component-recovery-and-fail-safe-ssr',
    retryPolicy:'one-candidate-per-qstash-request-up-to-three-automatic-attempts',
    automaticKeywordAttempts:3,
    manualKeywordAttempts:3,
    initialBatchSize:1,
    retryBatchSize:1,
    maxKeywordAttempts:3,
    maxRunSteps:72,
    maxRunMinutes:120,
    researchWindowHours:36,
    qualityGate:'pre-revision-accuracy-check-literal-fact-projection-and-final-deterministic-repair-v8034',
    completionRecovery:'candidate-id-stage-id-slug-alias-and-legacy-version-migration',
    feedSummaryPolicy:'verified-fact-sentences-only-no-object-coercion',
    relatedVideoPolicy:'direct-topic-relevance-trusted-channel-up-to-30-days',
    sourceDeduplication:'canonical-url-once-across-related-news-and-sources',
    feedReadPolicy:'index-first-then-published-content-source-of-truth-fallback',
    activeRunControl:'admin-current-run-id-and-immediate-cancel',
    publicTopCount:20,
    stageDurability:'publication-stage-plus-run-snapshot-candidate-and-slug-alias-self-healing-v8034',
    genericFactPolicy:'remove-generic-facts-and-rebuild-from-concrete-ledger-facts',
    legacyCompatibility:'fixed-keyword-content-stop-control-v8025',
    feedIndexCompatibility:'auto-repair-published-feed-indexes',
    feedRebuildCompatibility:'source-of-truth-force-rebuild-with-schema-validation',
    adminRuntimeCompatibility:'admin-runtime-recovery-v8026',
    stopFeedCompatibility:'stop-and-feed-recovery-v8030',
    feedFallbackCompatibility:'source-content-fallback-force-index-rebuild',
  });
}
